//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarsTable
    {
        public int CarLicenseNumber { get; set; }
        public int currentKm { get; set; }
        public string Image { get; set; }
        public bool isRentable { get; set; }
        public bool isDamaged { get; set; }
        public int carmodelID { get; set; }
        public int BranchId { get; set; }
        public int CarID { get; set; }
    }
}
