//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersTable
    {
        public int UserID { get; set; }
        public string FullName { get; set; }
        public Nullable<int> PassportID { get; set; }
        public string UserName { get; set; }
        public string BirthDate { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string Image { get; set; }
        public int MemberLevel { get; set; }
        public string Password { get; set; }
    }
}
